{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "bloggernetes.fullname" . }}
  labels:
    {{- include "bloggernetes.labels" . | nindent 4 }}
rules:
  - apiGroups: ["alpha.bloggernetes.davies.me.uk"]
    resources: ["blogposts", "blogpages"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "bloggernetes.fullname" . }}
  labels:
    {{- include "bloggernetes.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "bloggernetes.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "bloggernetes.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}